/*
  Local TinyML wake-word ping for Seeed Studio XIAO ESP32S3 Sense.

  This sketch does not use Edge Impulse.
  It uses model_data.h generated by training/train_local_wake_word.py.

  Required Arduino libraries:
  - ESP32 board package by Espressif (includes TFLiteMicro)
*/

#include <Arduino.h>
#include <ESP_I2S.h>
#include <HTTPClient.h>
#include <WiFi.h>
#include <TFLIteMicro.h>

#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/schema/schema_generated.h"

#include "model_data.h"

// ===== Edit these values first =====
const char *WIFI_SSID = "nisipeanu";
const char *WIFI_PASSWORD = "12345678";
const char *PC_SERVER_PING_URL = "http://10.123.21.208:8000/ping";
const char *PC_SERVER_COLLECT_URL = "http://10.123.21.208:8000/collect";

enum DeviceMode {
  MODE_WAKE_DETECT = 0,
  MODE_COLLECT_DATA = 1,
};

constexpr DeviceMode DEVICE_MODE = MODE_WAKE_DETECT;
// constexpr DeviceMode DEVICE_MODE = MODE_COLLECT_DATA;

constexpr float WAKE_WORD_THRESHOLD = 0.55f;
constexpr uint32_t WAKE_DEBOUNCE_MS = 3000;
constexpr float INPUT_TARGET_RMS = 0.04f;
constexpr float INPUT_MIN_GAIN = 0.5f;
constexpr float INPUT_MAX_GAIN = 20.0f;
constexpr bool INPUT_REMOVE_DC_OFFSET = true;
constexpr bool INPUT_APPLY_RMS_NORMALIZATION = false;
constexpr bool SPEECH_GATE_ENABLED = false;
constexpr float SPEECH_GATE_MIN_CENTERED_RMS = 0.0015f;
constexpr float SPEECH_GATE_MIN_P2P = 0.0200f;
constexpr float LISTEN_PHASE_SECONDS = 3.0f;
constexpr uint32_t POST_CYCLE_COOLDOWN_MS = 5000;
constexpr uint32_t COLLECT_POST_UPLOAD_DELAY_MS = 800;
// ==================================

constexpr int PDM_CLK_PIN = 42;
constexpr int PDM_DATA_PIN = 41;
constexpr int WINDOW_HOP_SAMPLES = kWakeWordInputSamples / 2;
constexpr float WINDOW_SECONDS = static_cast<float>(kWakeWordInputSamples) / static_cast<float>(kWakeWordSampleRate);
constexpr float WINDOW_HOP_SECONDS = static_cast<float>(WINDOW_HOP_SAMPLES) / static_cast<float>(kWakeWordSampleRate);
constexpr int LISTEN_PHASE_SAMPLES = static_cast<int>(LISTEN_PHASE_SECONDS * kWakeWordSampleRate);
constexpr int LISTEN_WINDOW_COUNT =
    (LISTEN_PHASE_SAMPLES <= kWakeWordInputSamples)
        ? 1
        : 1 + ((LISTEN_PHASE_SAMPLES - kWakeWordInputSamples + WINDOW_HOP_SAMPLES - 1) / WINDOW_HOP_SAMPLES);

#ifndef LED_BUILTIN
#define LED_BUILTIN 21
#endif

constexpr int LED_PIN = LED_BUILTIN;
constexpr bool LED_ACTIVE_LOW = true;

// Arena size with and without PSRAM.
constexpr int TENSOR_ARENA_SIZE_PSRAM = 300 * 1024;
constexpr int TENSOR_ARENA_SIZE_NO_PSRAM = 180 * 1024;

I2SClass I2S;

const tflite::Model *model = nullptr;
tflite::MicroInterpreter *interpreter = nullptr;
TfLiteTensor *input = nullptr;
TfLiteTensor *output = nullptr;

uint8_t *tensor_arena = nullptr;
int16_t *audio_window = nullptr;
size_t tensor_arena_size = 0;

uint32_t last_wake_ms = 0;
uint32_t inference_counter = 0;
int16_t discard_buffer[512];
float last_centered_rms = 0.0f;
float last_centered_p2p = 0.0f;

enum CollectLabel {
  COLLECT_WAKE = 0,
  COLLECT_NOT_WAKE = 1,
};

CollectLabel pending_collect_label = COLLECT_WAKE;

void set_led(bool on) {
  digitalWrite(LED_PIN, LED_ACTIVE_LOW ? !on : on);
}

void connect_wifi() {
  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);

  Serial.print("Connecting to Wi-Fi");
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println();
  Serial.print("Wi-Fi connected, IP address: ");
  Serial.println(WiFi.localIP());
}

void ensure_wifi() {
  if (WiFi.status() == WL_CONNECTED) {
    return;
  }

  Serial.println("Wi-Fi disconnected; reconnecting");
  WiFi.disconnect();
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);

  const uint32_t started = millis();
  while (WiFi.status() != WL_CONNECTED && millis() - started < 10000) {
    delay(250);
  }
}

bool start_microphone() {
  I2S.setPinsPdmRx(PDM_CLK_PIN, PDM_DATA_PIN);

  if (!I2S.begin(I2S_MODE_PDM_RX,
                 kWakeWordSampleRate,
                 I2S_DATA_BIT_WIDTH_16BIT,
                 I2S_SLOT_MODE_MONO)) {
    Serial.println("Failed to initialize PDM microphone");
    return false;
  }

  Serial.print("Microphone started at ");
  Serial.print(kWakeWordSampleRate);
  Serial.println(" Hz, 16-bit mono");
  return true;
}

bool read_pcm_bytes(uint8_t *destination, size_t bytes_to_read) {
  size_t bytes_read = 0;

  while (bytes_read < bytes_to_read) {
    const size_t n = I2S.readBytes(reinterpret_cast<char *>(destination + bytes_read),
                                   bytes_to_read - bytes_read);
    if (n == 0) {
      delay(1);
      continue;
    }
    bytes_read += n;
  }

  return true;
}

bool read_pcm_samples(int16_t *destination, size_t samples_to_read) {
  return read_pcm_bytes(reinterpret_cast<uint8_t *>(destination),
                        samples_to_read * sizeof(int16_t));
}

bool discard_pcm_samples(size_t samples_to_discard) {
  size_t remaining = samples_to_discard;
  while (remaining > 0) {
    const size_t chunk = remaining > 512 ? 512 : remaining;
    if (!read_pcm_samples(discard_buffer, chunk)) {
      return false;
    }
    remaining -= chunk;
  }
  return true;
}

void *allocate_memory(size_t bytes) {
  void *ptr = ps_malloc(bytes);
  if (ptr == nullptr) {
    ptr = malloc(bytes);
  }
  return ptr;
}

bool ensure_audio_window() {
  if (audio_window != nullptr) {
    return true;
  }

  audio_window = static_cast<int16_t *>(allocate_memory(kWakeWordInputSamples * sizeof(int16_t)));
  if (audio_window == nullptr) {
    Serial.println("Failed to allocate audio window buffer.");
    Serial.println("Enable PSRAM in board menu if available.");
    return false;
  }

  return true;
}

bool setup_tinyml() {
  const bool has_psram = psramFound();
  tensor_arena_size = has_psram ? TENSOR_ARENA_SIZE_PSRAM : TENSOR_ARENA_SIZE_NO_PSRAM;

  Serial.print("PSRAM found: ");
  Serial.println(has_psram ? "yes" : "no");
  Serial.print("Free heap: ");
  Serial.println(ESP.getFreeHeap());
  if (has_psram) {
    Serial.print("Free PSRAM: ");
    Serial.println(ESP.getFreePsram());
  }

  tensor_arena = static_cast<uint8_t *>(allocate_memory(tensor_arena_size));
  if (!ensure_audio_window()) {
    return false;
  }

  if (tensor_arena == nullptr) {
    Serial.print("Failed to allocate TinyML memory. arena=");
    Serial.print(tensor_arena_size);
    Serial.println(" bytes.");
    Serial.println("Enable PSRAM in board menu if available.");
    return false;
  }

  model = tflite::GetModel(wake_word_model_tflite);
  if (model->version() != TFLITE_SCHEMA_VERSION) {
    Serial.println("TFLite schema version mismatch");
    return false;
  }

  // Ops discovered from training/output/wake_word_model_int8.tflite
  static tflite::MicroMutableOpResolver<4> resolver;
  if (resolver.AddConv2D() != kTfLiteOk ||
      resolver.AddMean() != kTfLiteOk ||
      resolver.AddFullyConnected() != kTfLiteOk ||
      resolver.AddSoftmax() != kTfLiteOk) {
    Serial.println("Failed to register TinyML ops");
    return false;
  }

  static tflite::MicroInterpreter static_interpreter(
      model,
      resolver,
      tensor_arena,
      tensor_arena_size);

  interpreter = &static_interpreter;

  if (interpreter->AllocateTensors() != kTfLiteOk) {
    Serial.println("AllocateTensors() failed. Increase tensor arena or enable PSRAM.");
    return false;
  }

  input = interpreter->input(0);
  output = interpreter->output(0);

  Serial.print("TinyML model loaded. Input samples: ");
  Serial.println(kWakeWordInputSamples);
  return true;
}

void put_audio_in_input_tensor(const int16_t *samples) {
  float mean = 0.0f;
  if (INPUT_REMOVE_DC_OFFSET) {
    for (int i = 0; i < kWakeWordInputSamples; i++) {
      mean += static_cast<float>(samples[i]);
    }
    mean /= static_cast<float>(kWakeWordInputSamples);
  }

  float centered_min = 1.0f;
  float centered_max = -1.0f;
  float sum_sq = 0.0f;
  for (int i = 0; i < kWakeWordInputSamples; i++) {
    const float centered = (static_cast<float>(samples[i]) - mean) / 32768.0f;
    if (centered < centered_min) centered_min = centered;
    if (centered > centered_max) centered_max = centered;
    sum_sq += centered * centered;
  }
  last_centered_rms = sqrtf(sum_sq / static_cast<float>(kWakeWordInputSamples));
  last_centered_p2p = centered_max - centered_min;

  const int frame_size = kWakeWordInputSamples / kWakeWordFeatureCount;
  if (input->type == kTfLiteInt8) {
    for (int feature_index = 0; feature_index < kWakeWordFeatureCount; feature_index++) {
      float sum_abs = 0.0f;
      const int start = feature_index * frame_size;
      for (int i = 0; i < frame_size; i++) {
        const float centered = (static_cast<float>(samples[start + i]) - mean) / 32768.0f;
        sum_abs += fabsf(centered);
      }
      const float feature = constrain((sum_abs / static_cast<float>(frame_size)) * kWakeWordFeatureGain, 0.0f, 1.0f);
      int32_t quantized = static_cast<int32_t>(roundf(feature / input->params.scale)) + input->params.zero_point;
      quantized = constrain(quantized, -128, 127);
      input->data.int8[feature_index] = static_cast<int8_t>(quantized);
    }
    return;
  }

  if (input->type == kTfLiteFloat32) {
    for (int feature_index = 0; feature_index < kWakeWordFeatureCount; feature_index++) {
      float sum_abs = 0.0f;
      const int start = feature_index * frame_size;
      for (int i = 0; i < frame_size; i++) {
        const float centered = (static_cast<float>(samples[start + i]) - mean) / 32768.0f;
        sum_abs += fabsf(centered);
      }
      input->data.f[feature_index] = constrain((sum_abs / static_cast<float>(frame_size)) * kWakeWordFeatureGain, 0.0f, 1.0f);
    }
  }
}

float output_score(int index) {
  if (output->type == kTfLiteInt8) {
    return (static_cast<int>(output->data.int8[index]) - output->params.zero_point) * output->params.scale;
  }

  if (output->type == kTfLiteUInt8) {
    return (static_cast<int>(output->data.uint8[index]) - output->params.zero_point) * output->params.scale;
  }

  if (output->type == kTfLiteFloat32) {
    return output->data.f[index];
  }

  return 0.0f;
}

void print_scores() {
  Serial.print("Predictions:");
  for (int i = 0; i < kWakeWordLabelCount; i++) {
    Serial.print(" ");
    Serial.print(kWakeWordLabels[i]);
    Serial.print("=");
    Serial.print(output_score(i), 3);
  }
  Serial.println();
}

void print_audio_stats(const int16_t *samples, int count) {
  int16_t min_value = 32767;
  int16_t max_value = -32768;
  double sum_sq = 0.0;

  for (int i = 0; i < count; i++) {
    const int16_t value = samples[i];
    if (value < min_value) min_value = value;
    if (value > max_value) max_value = value;
    const double normalized = static_cast<double>(value) / 32768.0;
    sum_sq += normalized * normalized;
  }

  const float rms = sqrtf(static_cast<float>(sum_sq / static_cast<double>(count)));

  Serial.print("Audio min=");
  Serial.print(min_value);
  Serial.print(" max=");
  Serial.print(max_value);
  Serial.print(" rms=");
  Serial.println(rms, 4);
}

bool send_ping_to_server(float wake_score) {
  ensure_wifi();
  if (WiFi.status() != WL_CONNECTED) {
    Serial.println("Cannot send ping: Wi-Fi is not connected");
    return false;
  }

  WiFiClient client;
  HTTPClient http;

  if (!http.begin(client, PC_SERVER_PING_URL)) {
    Serial.println("HTTP begin failed");
    return false;
  }

  http.addHeader("Content-Type", "application/json");
  const String payload = "{\"device\":\"xiao_esp32s3_sense\",\"event\":\"wake_word\",\"score\":" + String(wake_score, 3) + "}";

  const int status_code = http.POST(payload);
  const String response = http.getString();
  http.end();

  Serial.print("Server status: ");
  Serial.println(status_code);
  Serial.println(response);

  return status_code >= 200 && status_code < 300;
}

const char *collect_label_name(CollectLabel label) {
  if (label == COLLECT_WAKE) return "wake";
  return "not_wake";
}

bool send_collection_clip_to_server(const int16_t *samples, size_t sample_count, CollectLabel label) {
  ensure_wifi();
  if (WiFi.status() != WL_CONNECTED) {
    Serial.println("Cannot upload clip: Wi-Fi is not connected");
    return false;
  }

  WiFiClient client;
  HTTPClient http;

  if (!http.begin(client, PC_SERVER_COLLECT_URL)) {
    Serial.println("HTTP begin failed for /collect");
    return false;
  }

  http.addHeader("Content-Type", "application/octet-stream");
  http.addHeader("X-Audio-Sample-Rate", String(kWakeWordSampleRate));
  http.addHeader("X-Audio-Bits-Per-Sample", "16");
  http.addHeader("X-Audio-Channels", "1");
  http.addHeader("X-Clip-Label", collect_label_name(label));

  const size_t byte_count = sample_count * sizeof(int16_t);
  uint8_t *payload = reinterpret_cast<uint8_t *>(const_cast<int16_t *>(samples));
  const int status_code = http.POST(payload, byte_count);
  const String response = http.getString();
  http.end();

  Serial.print("Collect upload status: ");
  Serial.println(status_code);
  Serial.println(response);

  return status_code >= 200 && status_code < 300;
}

void print_collect_help() {
  Serial.println("Collection commands:");
  Serial.println("  w -> capture/upload one WAKE clip");
  Serial.println("  n -> capture/upload one NOT_WAKE clip");
  Serial.println("  h -> show commands");
}

void run_collection_mode() {
  if (!Serial.available()) {
    delay(20);
    return;
  }

  const int incoming = Serial.read();
  if (incoming == 'h' || incoming == 'H') {
    print_collect_help();
    return;
  }

  if (incoming != 'w' && incoming != 'W' && incoming != 'n' && incoming != 'N') {
    return;
  }

  pending_collect_label = (incoming == 'w' || incoming == 'W') ? COLLECT_WAKE : COLLECT_NOT_WAKE;

  Serial.print("Speak now: capturing ");
  Serial.print(WINDOW_SECONDS, 1);
  Serial.print("s for label=");
  Serial.println(collect_label_name(pending_collect_label));

  if (!read_pcm_samples(audio_window, kWakeWordInputSamples)) {
    Serial.println("Audio capture failed in collection mode");
    return;
  }

  print_audio_stats(audio_window, kWakeWordInputSamples);

  if (send_collection_clip_to_server(audio_window, kWakeWordInputSamples, pending_collect_label)) {
    Serial.println("Clip uploaded");
  } else {
    Serial.println("Clip upload failed");
  }

  Serial.print("Pause ");
  Serial.print(static_cast<float>(COLLECT_POST_UPLOAD_DELAY_MS) / 1000.0f, 1);
  Serial.println("s...");
  delay(COLLECT_POST_UPLOAD_DELAY_MS);
  Serial.println("Ready for next command (w/n)");
}

void refill_full_audio_window() {
  read_pcm_samples(audio_window, kWakeWordInputSamples);
}

void slide_audio_window() {
  const int keep_samples = kWakeWordInputSamples / 2;
  const int new_samples = kWakeWordInputSamples - keep_samples;

  memmove(audio_window,
          audio_window + new_samples,
          keep_samples * sizeof(int16_t));

  read_pcm_samples(audio_window + keep_samples, new_samples);
}

void setup() {
  Serial.begin(115200);
  delay(1500);

  pinMode(LED_PIN, OUTPUT);
  set_led(false);

  Serial.println("XIAO ESP32S3 Sense local TinyML wake-word ping");
  Serial.print("Device mode: ");
  if (DEVICE_MODE == MODE_COLLECT_DATA) {
    Serial.println("DATA_COLLECTION");
  } else {
    Serial.println("WAKE_DETECTION");
  }
  Serial.print("Listening window: ");
  Serial.print(WINDOW_SECONDS, 2);
  Serial.println("s");
  Serial.print("Listen phase: ");
  Serial.print(LISTEN_PHASE_SECONDS, 2);
  Serial.println("s");
  Serial.print("Post-process cooldown: ");
  Serial.print(static_cast<float>(POST_CYCLE_COOLDOWN_MS) / 1000.0f, 1);
  Serial.println("s");
  Serial.print("Wake threshold: ");
  Serial.println(WAKE_WORD_THRESHOLD, 2);
  Serial.print("Inference windows per listen phase: ");
  Serial.println(LISTEN_WINDOW_COUNT);
  Serial.println("Each prediction is a rolling 2.0s window inside the listen phase.");

  connect_wifi();

  if (!start_microphone()) {
    while (true) {
      delay(1000);
    }
  }

  if (!ensure_audio_window()) {
    while (true) {
      delay(1000);
    }
  }

  if (DEVICE_MODE == MODE_WAKE_DETECT) {
    if (!setup_tinyml()) {
      while (true) {
        delay(1000);
      }
    }
  }

  Serial.println("Filling first audio window");
  refill_full_audio_window();
  if (DEVICE_MODE == MODE_COLLECT_DATA) {
    Serial.println("Collection mode ready.");
    print_collect_help();
  } else {
    Serial.println("Warmup complete.");
  }
}

void loop() {
  if (DEVICE_MODE == MODE_COLLECT_DATA) {
    run_collection_mode();
    return;
  }

  inference_counter++;

  Serial.print("Speak now (listening ");
  Serial.print(LISTEN_PHASE_SECONDS, 1);
  Serial.println("s) ...");

  if (!read_pcm_samples(audio_window, kWakeWordInputSamples)) {
    Serial.println("Audio capture failed while reading inference window");
    delay(200);
    return;
  }

  float best_scores[kWakeWordLabelCount];
  for (int i = 0; i < kWakeWordLabelCount; i++) {
    best_scores[i] = 0.0f;
  }

  float best_wake_score = -1.0f;
  int best_window = 0;

  for (int window_index = 0; window_index < LISTEN_WINDOW_COUNT; window_index++) {
    if (window_index > 0) {
      slide_audio_window();
    }

    print_audio_stats(audio_window, kWakeWordInputSamples);
    Serial.print("Processing window ");
    Serial.print(window_index + 1);
    Serial.print("/");
    Serial.print(LISTEN_WINDOW_COUNT);
    Serial.print(" (");
    Serial.print(WINDOW_SECONDS, 1);
    Serial.println("s)...");

    put_audio_in_input_tensor(audio_window);

    Serial.print("Signal centered_rms=");
    Serial.print(last_centered_rms, 5);
    Serial.print(" p2p=");
    Serial.println(last_centered_p2p, 4);

    if (SPEECH_GATE_ENABLED &&
        (last_centered_rms < SPEECH_GATE_MIN_CENTERED_RMS || last_centered_p2p < SPEECH_GATE_MIN_P2P)) {
      Serial.println("Speech gate: quiet/flat window -> skip this window");
      continue;
    }

    if (interpreter->Invoke() != kTfLiteOk) {
      Serial.println("TinyML inference failed");
      return;
    }

    print_scores();

    const float window_wake_score = output_score(kWakeWordIndex);
    if (window_wake_score > best_wake_score) {
      best_wake_score = window_wake_score;
      best_window = window_index + 1;
      for (int i = 0; i < kWakeWordLabelCount; i++) {
        best_scores[i] = output_score(i);
      }
    }
  }

  if (best_wake_score < 0.0f) {
    Serial.println("No inference window accepted; treating as not_wake.");
    Serial.print("Cooldown ");
    Serial.print(static_cast<float>(POST_CYCLE_COOLDOWN_MS) / 1000.0f, 1);
    Serial.println("s...");
    delay(POST_CYCLE_COOLDOWN_MS);
    return;
  }

  Serial.print("Best window: ");
  Serial.print(best_window);
  Serial.print("/");
  Serial.print(LISTEN_WINDOW_COUNT);
  Serial.print(" Predictions:");
  for (int i = 0; i < kWakeWordLabelCount; i++) {
    Serial.print(" ");
    Serial.print(kWakeWordLabels[i]);
    Serial.print("=");
    Serial.print(best_scores[i], 3);
  }
  Serial.println();

  const float wake_score = best_wake_score;
  const uint32_t now = millis();
  const bool debounce_elapsed = last_wake_ms == 0 || now - last_wake_ms >= WAKE_DEBOUNCE_MS;

  if (wake_score > WAKE_WORD_THRESHOLD && debounce_elapsed) {
    last_wake_ms = now;

    Serial.print("Wake word detected with confidence ");
    Serial.println(wake_score, 3);

    set_led(true);
    if (send_ping_to_server(wake_score)) {
      Serial.println("Ping sent");
    } else {
      Serial.println("Ping failed");
    }
    set_led(false);
  } else if (wake_score > WAKE_WORD_THRESHOLD && !debounce_elapsed) {
    const uint32_t remaining_ms = WAKE_DEBOUNCE_MS - (now - last_wake_ms);
    Serial.print("Detected but internal debounce active for ");
    Serial.print(remaining_ms);
    Serial.println(" ms");
  }

  Serial.print("Cooldown ");
  Serial.print(static_cast<float>(POST_CYCLE_COOLDOWN_MS) / 1000.0f, 1);
  Serial.println("s...");
  delay(POST_CYCLE_COOLDOWN_MS);
}
